on:
  push:
    branches:
      - main

name: Build Test Apps

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # - uses: subosito/flutter-action@v2.12.0
      #   with:
      #     channel: 'stable'
      # - run: flutter pub get
      # - run: flutter build apk --release 
      # #--split-per-abi
      # - name: Archive files
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install zip
      #     zip -r archive.zip *
      # - name: Upload to gdrive
      #   uses: adityak74/google-drive-upload-git-action@main
      #   with:
      #     credentials: ${{ secrets.CREDENTIALS }}
      #     filename: "build/app/outputs/apk/release/*"
      #     folderId: ${{ secrets.FOLDERID }}
      #     name: "apk.zip" # optional string
      #     overwrite: "true"

      # - id: set_var
      #   run: |
      #     content=`cat json/embeds.json`
      #     content="${content//'%'/'%25'}"
      #     content="${content//$'\n'/'%0A'}"
      #     content="${content//$'\r'/'%0D'}"
      #     echo "packageJson=$content" >> "$GITHUB_OUTPUT"

      - name: show env
        env:
          JSON_ARCHIVE: '[{"title": "hola mundo"}]'

        run: echo "$JSON_ARCHIVE"

      - name: Actions for Discord
        env:
           DISCORD_WEBHOOK: https://discord.com/api/webhooks/${{ secrets.WEBHOOK_ID }}/${{ secrets.WEBHOOK_TOKEN }}
           DISCORD_USERNAME: Drive Apk Bot
           DISCORD_AVATAR: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
          #  DISCORD_EMBEDS: ${{ toJson(steps.set_var.outputs.packageJson) }} 
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: ${{ secrets.MESSAGE_DISCORD }}  



      # - name: Discord Message Notify
      #   uses: appleboy/discord-action@v1.0.0
      #   with:
      #     webhook_id: ${{ secrets.WEBHOOK_ID }}
      #     webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
      #     file: "build/app/outputs/apk/release/*"
      #     avatar_url: "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png"
      #     username: "DriveApk bot"
      #     message: ${{ secrets.MESSAGE_DISCORD }}
             
      
      # - name: Send notify a telegram group
      #   uses: robotomize/notify-telegram@v0.1.0
      #   if: always()
      #   with:
      #     chat: ${{ secrets.CHATID }} # user id or channel name secret
      #     token: ${{ secrets.TELEGRAMTOKEN }} # token secret
      #     status: ${{ job.status }} # do not modify this line
      #     message: ${{ secrets.MESSAGE }} # custom message